swagger: '2.0'
info:
  title: Swaggy Jenkins
  description: Jenkins remote access API
  version: "0.0.1"
  contact:
    name: Cliffano Subagio
    url: http://github.com/cliffano/swaggy-jenkins
    email: blah@cliffano.com
schemes:
  - http
  - https
basePath: /
securityDefinitions:
  jenkins_auth:
    type: basic
paths:
  /crumbIssuer/api/json:
    get:
      description: Get crumb
      operationId: getCrumb
      produces:
        - application/json
      responses:
        200:
          description: Successfully get crumb
          schema:
            $ref: "#/definitions/DefaultCrumbIssuer"
      tags:
        - jenkins
  /queue/api/json:
    get:
      description: Get queue
      operationId: getQueue
      produces:
        - application/json
      responses:
        200:
          description: Successfully get queue
          schema:
            $ref: "#/definitions/Queue"
      tags:
        - jenkins
definitions:
  Cause$UserIdCause:
    type: object
    properties:
      _class:
        type: string
      shortDescription:
        type: string
      userId:
        type: string
      userName:
        type: string
  CauseAction:
    type: object
    properties:
      _class:
        type: string
      causes:
        type: array
        items:
          $ref: '#/definitions/Cause$UserIdCause'
  DefaultCrumbIssuer:
    type: object
    properties:
      _class:
        type: string
      crumb:
        type: string
      crumbRequestField:
        type: string
  FreeStyleProject:
    type: object
    properties:
      _class:
        type: string
      name:
        type: string
      url:
        type: string
      color:
        type: string
  Queue$BlockedItem:
    type: object
    properties:
      _class:
        type: string
      actions:
        type: array
        items:
          $ref: '#/definitions/CauseAction'
      id:
        type: integer
      inQueueSince:
        type: integer
      params:
        type: string
      task:
        $ref: '#/definitions/FreeStyleProject'
      url:
        type: string
      why:
        type: string
      buildableStartMilliseconds:
        type: integer
  Queue:
    type: object
    properties:
      _class:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/Queue$BlockedItem'
